"""Pure input-deck transforms for periodic LAMMPS restart/resume.

The prepared v0.2 deck remains the scientific source of truth.  These helpers
only add restart instrumentation or derive a restart deck from commands already
present in that reviewed generated deck.  They never invent thermodynamic
parameters or model settings.
"""
from __future__ import annotations

import hashlib

CHECKPOINT_FILES = ("checkpoint.1.restart", "checkpoint.2.restart")
RESTART_VARIABLE = "RESTART_FILE"


class RestartDeckError(ValueError):
    pass


def sha256_text(text: str) -> str:
    return "sha256:" + hashlib.sha256(text.encode("utf-8")).hexdigest()


def _line(lines: list[str], prefix: str, *, required: bool = True) -> str | None:
    matches = [line for line in lines if line.strip().startswith(prefix)]
    if not matches and not required:
        return None
    if len(matches) != 1:
        raise RestartDeckError(f"generated deck must contain exactly one {prefix!r} command")
    return matches[0]


def _validate_interval(interval: int, total_steps: int) -> None:
    if isinstance(interval, bool) or not isinstance(interval, int) or interval <= 0:
        raise RestartDeckError("checkpoint interval must be a positive integer")
    if isinstance(total_steps, bool) or not isinstance(total_steps, int) or total_steps <= 0:
        raise RestartDeckError("total steps must be a positive integer")
    if interval > total_steps:
        raise RestartDeckError("checkpoint interval cannot exceed total steps")


def instrument_fresh(deck: str, interval: int, total_steps: int) -> str:
    """Add two-file periodic restart output immediately before the reviewed run."""

    _validate_interval(interval, total_steps)
    lines = deck.splitlines()
    if any(line.strip().startswith("read_restart") for line in lines):
        raise RestartDeckError("fresh generated deck unexpectedly reads a restart")
    if any(line.strip().startswith("restart ") for line in lines):
        raise RestartDeckError("fresh generated deck already contains restart instrumentation")
    expected_run = f"run             {total_steps}"
    indices = [index for index, line in enumerate(lines) if line.strip() == expected_run.strip()]
    if len(indices) != 1:
        raise RestartDeckError("fresh generated deck run command differs from approved total steps")
    marker = f'MLIPFLOW_LAMMPS_COMPLETED step={total_steps}'
    if sum(marker in line for line in lines) != 1:
        raise RestartDeckError("fresh generated deck completion marker is invalid")
    checkpoint = f"restart         {interval} {CHECKPOINT_FILES[0]} {CHECKPOINT_FILES[1]}"
    lines.insert(indices[0], checkpoint)
    return "\n".join(lines) + "\n"


def build_resume(deck: str, interval: int, total_steps: int) -> str:
    """Derive a restart input that restores the saved Nose-Hoover fix state.

    LAMMPS restart files contain atom/cell/timestep state and the internal state
    written by fix nvt/npt, but fix commands themselves are not stored.  The
    resume deck therefore reuses the exact generated fix line (same ID/style and
    parameters), reissues the MLIP pair commands, and runs *up to* the original
    global target step.
    """

    _validate_interval(interval, total_steps)
    lines = deck.splitlines()
    pair_style = _line(lines, "pair_style")
    pair_coeff = _line(lines, "pair_coeff")
    timestep = _line(lines, "timestep")
    thermo = _line(lines, "thermo ")
    thermo_style = _line(lines, "thermo_style")
    dump = _line(lines, "dump ")
    dump_modify = _line(lines, "dump_modify")
    fix = _line(lines, "fix ")
    write_data = _line(lines, "write_data")
    write_restart = _line(lines, "write_restart")
    marker_line = _line(lines, "print ")
    velocity = _line(lines, "velocity ")
    if velocity is None:
        raise RestartDeckError("fresh generated deck lacks its initial velocity command")
    marker = f"MLIPFLOW_LAMMPS_COMPLETED step={total_steps}"
    if marker not in str(marker_line):
        raise RestartDeckError("fresh generated deck completion marker does not bind total steps")
    fix_tokens = str(fix).split()
    if len(fix_tokens) < 4 or fix_tokens[0] != "fix" or fix_tokens[1] != "mlipflow" or fix_tokens[2] != "all" or fix_tokens[3] not in {"nvt", "npt"}:
        raise RestartDeckError("restart contract supports only the generated fix mlipflow all nvt/npt")

    checkpoint = f"restart         {interval} {CHECKPOINT_FILES[0]} {CHECKPOINT_FILES[1]}"
    resume = [
        "# Generated by MLIPFlow from the approved fresh deck for binary restart continuation.",
        "newton          on",
        f"read_restart    ${{{RESTART_VARIABLE}}}",
        "atom_modify     map yes",
        str(pair_style),
        str(pair_coeff),
        str(timestep),
        str(thermo),
        str(thermo_style),
        str(dump),
        str(dump_modify),
        str(fix),
        checkpoint,
        f"run             {total_steps} upto",
        str(write_data),
        str(write_restart),
        str(marker_line),
        "",
    ]
    text = "\n".join(resume)
    if "velocity" in text:
        raise RestartDeckError("resume deck must not reinitialize velocities")
    if "${MODEL_FILE}" not in text or f"${{{RESTART_VARIABLE}}}" not in text:
        raise RestartDeckError("resume deck lacks portable model/restart variables")
    return text
