name: tests

on:
  push:
  pull_request:

jobs:
  python312:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install --upgrade pip
      - run: python -m pip install '.[dev,local]'
      - run: pytest -q
      - run: ruff check mlipflow tests examples
